### ISSUE TITLE
Put the automatic clock in Stages instead of "Delay Zero"

### ISSUE THREAD

**Issue by Pouf842** [PleasingFungus/Silicon-Zeroes#79]
The clock is set automatically for the first time in Delay Zero, although players can complete that before all the other branch ("Slowstall", "Combiner", "Swap", "Copier"). I completed Delay Zero (where I've been told "No more manually adjusting the clock"), then went to complete "Copier", and hence forgot to adjust the clock, and got stuck for a bit.

Wouldn't it be better to put the automation in Stages, so that the player had inevitably complete all the "manual clock adjustment" levels ?

**Comment by PleasingFungus** [comment]
I don't want to introduce a bunch of things in one level. 'Delay Zero' is the 'here's the automatic clock' puzzle; 'Stages' teaches something much more complex, and I don't want to introduce more confusion into that mix.

What I could do is change it so that you can only do Delay Zero after Copier. I prefer having puzzles in parallel when possible, but do you think that'd be less confusing?

**Comment by Pouf842** [comment]
Well for the manual/automatic adjustment, yes, but for anything else, I can't say, really.
I'll let you judge.

**Comment by PleasingFungus** [comment]
Did it anyway, in 36022c48.
